package com.example.delivery_zalyaeva_shift_2025.ui.theme

import androidx.compose.ui.graphics.Color

val BackgroundPrimary = Color(0xFFFFFFFF)
val BackgroundSecondary = Color(0xFFF3F4F6)
val BackgroundTertiary = Color(0xFFF9FAFB)
val BackgroundDisable = Color(0xFFF3F4F6)
val TextPrimary = Color(0xFF141C24)
val TextSecondary = Color(0xFF344051)
val TextTertiary = Color(0xFF637083)
val TextQuartenery = Color(0xFF97A1AF)
val TextInvert = Color(0xFFFFFFFF)
val TextError = Color(0xFFF64C4C)
val BorderExtraLight = Color(0xFFE3E5E5)
val BorderLight = Color(0xFFCED2DA)
val BorderMedium = Color(0xFF97A1AF)
val IndicatorWhite = Color(0xFFFFFFFF)
val IndicatorLight = Color(0xFFCED2DA)
val IndicatorMedium = Color(0xFF97A1AF)
val IndicatorNormal = Color(0xFF141C24)
val IndicatorError = Color(0xFFF64C4C)
val IndicatorAttention = Color(0xFFFFB219)
val IndicatorPositive = Color(0xFF40BF7F)
val BackgroundBrand = Color(0xFF1975FF)
val BackgroundPressedPrimary = Color(0xFF1975FF)
val BackgroundHoverPrimary = Color(0xFF0052CC)
val BackgroundBrandExtraLight = Color(0xFFCCE0FF)
val TextBrandDisabled = Color(0xFFCCE0FF)
val IndicatorFocused = Color(0xFF4C94FF)
val IndicatorFocusedAlternative = Color(0xFF4C94FF)
val BackgroundOverlay = Color(0x2121213D)
val BackgroundLight = Color(0xFFF2F4F7)